// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/Helper/metro_helper/models/trip_details_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7550343634550854417),
    name: 'TripDetailsModel',
    lastPropertyId: const obx_int.IdUid(12, 5706528965651627420),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3411210631891118254),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3452321596232686419),
        name: 'startStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 661791038983604534),
        name: 'finalStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1655135241548333685),
        name: 'stationCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2306957780748800444),
        name: 'time',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4155350882499762217),
        name: 'ticketPrice',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1695552649970896872),
        name: 'transfer',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3834310563968879556),
        name: 'isFav',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7060455526065150359),
        name: 'startColorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5706528965651627420),
        name: 'finalColorValue',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 7550343634550854417),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [1545752483839365043, 5729817248310010087],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    TripDetailsModel: obx_int.EntityDefinition<TripDetailsModel>(
      model: _entities[0],
      toOneRelations: (TripDetailsModel object) => [],
      toManyRelations: (TripDetailsModel object) => {},
      getId: (TripDetailsModel object) => object.id,
      setId: (TripDetailsModel object, int id) {
        object.id = id;
      },
      objectToFB: (TripDetailsModel object, fb.Builder fbb) {
        final startStationOffset = object.startStation == null
            ? null
            : fbb.writeString(object.startStation!);
        final finalStationOffset = object.finalStation == null
            ? null
            : fbb.writeString(object.finalStation!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, startStationOffset);
        fbb.addOffset(2, finalStationOffset);
        fbb.addInt64(3, object.stationCount);
        fbb.addFloat64(4, object.time);
        fbb.addInt64(5, object.ticketPrice);
        fbb.addInt64(6, object.transfer);
        fbb.addBool(7, object.isFav);
        fbb.addInt64(10, object.startColorValue);
        fbb.addInt64(11, object.finalColorValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final finalStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final stationCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final timeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final transferParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final ticketPriceParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object =
            TripDetailsModel(
                startStation: startStationParam,
                finalStation: finalStationParam,
                stationCount: stationCountParam,
                time: timeParam,
                transfer: transferParam,
                ticketPrice: ticketPriceParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..isFav = const fb.BoolReader().vTableGet(
                buffer,
                rootOffset,
                18,
                false,
              )
              ..startColorValue = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                24,
              )
              ..finalColorValue = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                26,
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TripDetailsModel] entity fields to define ObjectBox queries.
class TripDetailsModel_ {
  /// See [TripDetailsModel.id].
  static final id = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[0].properties[0],
  );

  /// See [TripDetailsModel.startStation].
  static final startStation = obx.QueryStringProperty<TripDetailsModel>(
    _entities[0].properties[1],
  );

  /// See [TripDetailsModel.finalStation].
  static final finalStation = obx.QueryStringProperty<TripDetailsModel>(
    _entities[0].properties[2],
  );

  /// See [TripDetailsModel.stationCount].
  static final stationCount = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[0].properties[3],
  );

  /// See [TripDetailsModel.time].
  static final time = obx.QueryDoubleProperty<TripDetailsModel>(
    _entities[0].properties[4],
  );

  /// See [TripDetailsModel.ticketPrice].
  static final ticketPrice = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[0].properties[5],
  );

  /// See [TripDetailsModel.transfer].
  static final transfer = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[0].properties[6],
  );

  /// See [TripDetailsModel.isFav].
  static final isFav = obx.QueryBooleanProperty<TripDetailsModel>(
    _entities[0].properties[7],
  );

  /// See [TripDetailsModel.startColorValue].
  static final startColorValue = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[0].properties[8],
  );

  /// See [TripDetailsModel.finalColorValue].
  static final finalColorValue = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[0].properties[9],
  );
}
