// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/Helper/metro_helper/models/station_model.dart';
import 'core/Helper/metro_helper/models/trip_details_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2825235653140666416),
    name: 'RouteModel',
    lastPropertyId: const obx_int.IdUid(3, 3902969222554191420),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 237581360385689532),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3035266457986810426),
        name: 'routeOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3902969222554191420),
        name: 'tripId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 6226777685108691738),
        relationField: 'trip',
        relationTarget: 'TripDetailsModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'stations',
        srcEntity: 'StationModel',
        srcField: 'route',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1445322410143671425),
    name: 'StationModel',
    lastPropertyId: const obx_int.IdUid(10, 4209649772072915454),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1513336195971663537),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3492081775787736561),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3824519381112926179),
        name: 'transferBetween',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4004402168212960973),
        name: 'index',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5737876211741482316),
        name: 'order',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 190972046936594633),
        name: 'travellingTime',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1547704601023174891),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7644310271926713926),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2832706030211150874),
        name: 'lineColorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4209649772072915454),
        name: 'routeId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1624049542615595591),
        relationField: 'route',
        relationTarget: 'RouteModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5256849792098855863),
    name: 'TripDetailsModel',
    lastPropertyId: const obx_int.IdUid(10, 7220803646058034),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6107042643755836992),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4360307740014160483),
        name: 'startStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3926070317514643472),
        name: 'finalStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4862764391052495899),
        name: 'startColorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8174015710108294317),
        name: 'finalColorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3788719616545067975),
        name: 'stationCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 347921358801670025),
        name: 'time',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 905261289110152498),
        name: 'ticketPrice',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1269217066113251233),
        name: 'transfer',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7220803646058034),
        name: 'isFav',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'routes',
        srcEntity: 'RouteModel',
        srcField: 'trip',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 5256849792098855863),
    lastIndexId: const obx_int.IdUid(2, 1624049542615595591),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    RouteModel: obx_int.EntityDefinition<RouteModel>(
      model: _entities[0],
      toOneRelations: (RouteModel object) => [object.trip],
      toManyRelations: (RouteModel object) => {
        obx_int.RelInfo<StationModel>.toOneBacklink(
          10,
          object.id,
          (StationModel srcObject) => srcObject.route,
        ): object.stations,
      },
      getId: (RouteModel object) => object.id,
      setId: (RouteModel object, int id) {
        object.id = id;
      },
      objectToFB: (RouteModel object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.routeOrder);
        fbb.addInt64(2, object.trip.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final routeOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = RouteModel(routeOrder: routeOrderParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.trip.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.trip.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<RouteModel>(
          object.stations,
          store,
          obx_int.RelInfo<StationModel>.toOneBacklink(
            10,
            object.id,
            (StationModel srcObject) => srcObject.route,
          ),
        );
        return object;
      },
    ),
    StationModel: obx_int.EntityDefinition<StationModel>(
      model: _entities[1],
      toOneRelations: (StationModel object) => [object.route],
      toManyRelations: (StationModel object) => {},
      getId: (StationModel object) => object.id,
      setId: (StationModel object, int id) {
        object.id = id;
      },
      objectToFB: (StationModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final transferBetweenOffset = object.transferBetween == null
            ? null
            : fbb.writeString(object.transferBetween!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, transferBetweenOffset);
        fbb.addInt64(3, object.index);
        fbb.addInt64(4, object.order);
        fbb.addFloat64(5, object.travellingTime);
        fbb.addFloat64(6, object.longitude);
        fbb.addFloat64(7, object.latitude);
        fbb.addInt64(8, object.lineColorValue);
        fbb.addInt64(9, object.route.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final indexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final travellingTimeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final transferBetweenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final lineColorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object =
            StationModel(
                name: nameParam,
                latitude: latitudeParam,
                longitude: longitudeParam,
                index: indexParam,
                travellingTime: travellingTimeParam,
                transferBetween: transferBetweenParam,
                lineColorValue: lineColorValueParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..order = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                12,
              );
        object.route.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.route.attach(store);
        return object;
      },
    ),
    TripDetailsModel: obx_int.EntityDefinition<TripDetailsModel>(
      model: _entities[2],
      toOneRelations: (TripDetailsModel object) => [],
      toManyRelations: (TripDetailsModel object) => {
        obx_int.RelInfo<RouteModel>.toOneBacklink(
          3,
          object.id,
          (RouteModel srcObject) => srcObject.trip,
        ): object.routes,
      },
      getId: (TripDetailsModel object) => object.id,
      setId: (TripDetailsModel object, int id) {
        object.id = id;
      },
      objectToFB: (TripDetailsModel object, fb.Builder fbb) {
        final startStationOffset = object.startStation == null
            ? null
            : fbb.writeString(object.startStation!);
        final finalStationOffset = object.finalStation == null
            ? null
            : fbb.writeString(object.finalStation!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, startStationOffset);
        fbb.addOffset(2, finalStationOffset);
        fbb.addInt64(3, object.startColorValue);
        fbb.addInt64(4, object.finalColorValue);
        fbb.addInt64(5, object.stationCount);
        fbb.addFloat64(6, object.time);
        fbb.addInt64(7, object.ticketPrice);
        fbb.addInt64(8, object.transfer);
        fbb.addBool(9, object.isFav);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final finalStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final stationCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final timeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final transferParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final ticketPriceParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object =
            TripDetailsModel(
                startStation: startStationParam,
                finalStation: finalStationParam,
                stationCount: stationCountParam,
                time: timeParam,
                transfer: transferParam,
                ticketPrice: ticketPriceParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..startColorValue = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                10,
              )
              ..finalColorValue = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                12,
              )
              ..isFav = const fb.BoolReader().vTableGet(
                buffer,
                rootOffset,
                22,
                false,
              );
        obx_int.InternalToManyAccess.setRelInfo<TripDetailsModel>(
          object.routes,
          store,
          obx_int.RelInfo<RouteModel>.toOneBacklink(
            3,
            object.id,
            (RouteModel srcObject) => srcObject.trip,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RouteModel] entity fields to define ObjectBox queries.
class RouteModel_ {
  /// See [RouteModel.id].
  static final id = obx.QueryIntegerProperty<RouteModel>(
    _entities[0].properties[0],
  );

  /// See [RouteModel.routeOrder].
  static final routeOrder = obx.QueryIntegerProperty<RouteModel>(
    _entities[0].properties[1],
  );

  /// See [RouteModel.trip].
  static final trip = obx.QueryRelationToOne<RouteModel, TripDetailsModel>(
    _entities[0].properties[2],
  );

  /// see [RouteModel.stations]
  static final stations = obx.QueryBacklinkToMany<StationModel, RouteModel>(
    StationModel_.route,
  );
}

/// [StationModel] entity fields to define ObjectBox queries.
class StationModel_ {
  /// See [StationModel.id].
  static final id = obx.QueryIntegerProperty<StationModel>(
    _entities[1].properties[0],
  );

  /// See [StationModel.name].
  static final name = obx.QueryStringProperty<StationModel>(
    _entities[1].properties[1],
  );

  /// See [StationModel.transferBetween].
  static final transferBetween = obx.QueryStringProperty<StationModel>(
    _entities[1].properties[2],
  );

  /// See [StationModel.index].
  static final index = obx.QueryIntegerProperty<StationModel>(
    _entities[1].properties[3],
  );

  /// See [StationModel.order].
  static final order = obx.QueryIntegerProperty<StationModel>(
    _entities[1].properties[4],
  );

  /// See [StationModel.travellingTime].
  static final travellingTime = obx.QueryDoubleProperty<StationModel>(
    _entities[1].properties[5],
  );

  /// See [StationModel.longitude].
  static final longitude = obx.QueryDoubleProperty<StationModel>(
    _entities[1].properties[6],
  );

  /// See [StationModel.latitude].
  static final latitude = obx.QueryDoubleProperty<StationModel>(
    _entities[1].properties[7],
  );

  /// See [StationModel.lineColorValue].
  static final lineColorValue = obx.QueryIntegerProperty<StationModel>(
    _entities[1].properties[8],
  );

  /// See [StationModel.route].
  static final route = obx.QueryRelationToOne<StationModel, RouteModel>(
    _entities[1].properties[9],
  );
}

/// [TripDetailsModel] entity fields to define ObjectBox queries.
class TripDetailsModel_ {
  /// See [TripDetailsModel.id].
  static final id = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[2].properties[0],
  );

  /// See [TripDetailsModel.startStation].
  static final startStation = obx.QueryStringProperty<TripDetailsModel>(
    _entities[2].properties[1],
  );

  /// See [TripDetailsModel.finalStation].
  static final finalStation = obx.QueryStringProperty<TripDetailsModel>(
    _entities[2].properties[2],
  );

  /// See [TripDetailsModel.startColorValue].
  static final startColorValue = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[2].properties[3],
  );

  /// See [TripDetailsModel.finalColorValue].
  static final finalColorValue = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[2].properties[4],
  );

  /// See [TripDetailsModel.stationCount].
  static final stationCount = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[2].properties[5],
  );

  /// See [TripDetailsModel.time].
  static final time = obx.QueryDoubleProperty<TripDetailsModel>(
    _entities[2].properties[6],
  );

  /// See [TripDetailsModel.ticketPrice].
  static final ticketPrice = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[2].properties[7],
  );

  /// See [TripDetailsModel.transfer].
  static final transfer = obx.QueryIntegerProperty<TripDetailsModel>(
    _entities[2].properties[8],
  );

  /// See [TripDetailsModel.isFav].
  static final isFav = obx.QueryBooleanProperty<TripDetailsModel>(
    _entities[2].properties[9],
  );

  /// see [TripDetailsModel.routes]
  static final routes = obx.QueryBacklinkToMany<RouteModel, TripDetailsModel>(
    RouteModel_.trip,
  );
}
